# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c9e08a596f7b43b64dfd0d6be7c9904e3256dfef54fe2ca1eaf875bc2911b0b2620af6aab6eda89de9c11c6d5917ba818861fe395e74d6f440c6af7f6e507b5

test:
  secret_key_base: ffa85602aa5a953a49d1c5e1980d0e450739c3d785070f92240de04c4c4e2796e24d1cf86e9ba5db623e115cb78661093e518378eabe30b964792b0a2208e62e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
